### ISSUE TITLE
这个bug大不大

### ISSUE THREAD

**Issue by yvanda** [CatchZeng/CATClearProjectTool#1]
![2017-02-21 pm4 34 56](https://cloud.githubusercontent.com/assets/3233066/23156909/cefc6d38-f853-11e6-93be-78d5692ccb7b.png)

**Comment by zuolingfeng** [comment]
是啊，一点search就变大，看不到结果，缩小也找不到地方呀，
这样的项目要给star，扎心了啊，

**Comment by zhihuilong** [comment]
我fork了这个项目并且改好，你们可以看看 [zhihuilong/CATClearProjectTool](https://github.com/zhihuilong/CATClearProjectTool)
